-- MySQL Script generated by MySQL Workbench
-- Thu Nov 16 12:58:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project_resa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_resa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_resa` DEFAULT CHARACTER SET utf8 ;
USE `project_resa` ;

-- -----------------------------------------------------
-- Table `project_resa`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_resa`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `phone` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_resa`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_resa`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` INT NOT NULL,
  `roomType` VARCHAR(255) NOT NULL,
  `pricePerNight` DECIMAL(10,2) NOT NULL,
  `isAvailable` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_resa`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_resa`.`reservation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NOT NULL,
  `endDate` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  `numberOfAdults` INT NOT NULL,
  `numberOfChildren` INT NOT NULL,
  `room_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservation_room_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_reservation_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `project_resa`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `project_resa`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_resa`.`reservationOption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_resa`.`reservationOption` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `optionName` VARCHAR(255) NOT NULL,
  `optionPrice` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_resa`.`reservationOption_has_reservation`
-- -----------------------------------------------------

-------------------------------------------------------------------------------
--trigger
CREATE TRIGGER before_booking_insert_update
BEFORE INSERT OR UPDATE ON `project_resa`.`booking`
FOR EACH ROW
BEGIN
    DECLARE roomIsReserved INT;

    SELECT `isReserved` INTO roomIsReserved
    FROM `project_resa`.`room`
    WHERE `id` = NEW.`room_id`;
